spring:
  config:
    import: "optional:configtree:/mnt/secrets/sscs/"
    activate:
      on-profile: smoke
  application:
    name: TyaNotificationsService
  main:
    allow-bean-definition-overriding: true