server.port: ${PORT:8081}

spring:
  application:
    name: TyaNotificationsService
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${JOB_SCHEDULER_DB_HOST:localhost}:${JOB_SCHEDULER_DB_PORT:5432}/${JOB_SCHEDULER_DB_NAME:sscsjobscheduler}${JOB_SCHEDULER_DB_CONNECTION_OPTIONS:}
    username: ${JOB_SCHEDULER_DB_USERNAME:sscsjobscheduler}
    password: ${JOB_SCHEDULER_DB_PASSWORD:sscsjobscheduler}
    properties:
      charSet: UTF-8
    # http://tomcat.apache.org/tomcat-7.0-doc/jdbc-pool.html#Common_Attributes
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  userId: ${CORE_CASE_DATA_USER_ID:16}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}

idam:
  url: ${IDAM_URL:http://localhost:4501}
  s2s-auth:
    totp_secret: ${IDAM.S2S-AUTH.TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM.S2S-AUTH.MICROSERVICE:sscs}
    url: ${IDAM.S2S-AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:SSCS_SYSTEM_UPDATE}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:SSCS_SYSTEM_UPDATE}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_SSCS_URL:https://localhost:9000/poc}

management:
  security.enabled: ${MANAGEMENT_SECURITY_ENABLED:false}
  info.git.mode: full
  endpoints:
    health.show-details: always

gov.uk.notification.api.key: ${NOTIFICATION_API_KEY:emailnotificationkey}
subscription.hmac.secret.text: ${EMAIL_MAC_SECRET_TEXT:our-big-secret}

hmcts.phone.number: 0300 123 1142

evidence.submission.info.link: ${EVIDENCE_SUBMISSION_INFO_LINK:http://localhost:3000/evidence/appeal_id}
manage.emails.link: ${SSCS_MANAGE_EMAILS_LINK:http://localhost:3000/manage-email-notifications/mac}
track.appeal.link: ${SSCS_TRACK_YOUR_APPEAL_LINK:http://localhost:3000/trackyourappeal/appeal_id}
hearing.info.link: ${HEARING_INFO_LINK:http://localhost:3000/abouthearing/appeal_id}
claiming.expenses.link: ${CLAIMING_EXPENSES_LINK:http://localhost:3000/expenses/appeal_id}

job.scheduler:
  enabled: ${JOB_SCHEDULER_ENABLED:true}
  retryPolicy:
    maxNumberOfJobExecutions: 2
    delayBetweenAttemptsInMs: 1000

notification:
  appealReceived.emailId: ${APPEAL_RECEIVED_EMAIL_TEMPLATE_ID:b90df52f-c628-409c-8875-4b0b9663a053}
  responseReceived.emailId: ${RESPONSE_RECEIVED_EMAIL_TEMPLATE_ID:1e13bd2d-9ae0-4030-89b9-a0ef65ec36ef}
  evidenceReceived:
    emailId: ${EVIDENCE_RECEIVED_EMAIL_TEMPLATE_ID:c5654134-2e13-4541-ac73-334a5b5cdbb6}
    smsId: ${EVIDENCE_RECEIVED_SMS_TEMPLATE_ID:74bda35f-040b-4355-bda3-faf0e4f5ae6e}
  hearingAdjourned:
    emailId: ${HEARING_ADJOURNED_EMAIL_TEMPLATE_ID:07b9738d-d6ba-4736-86f6-7102776f57a2}
    smsId: ${HEARING_ADJOURNED_SMS_TEMPLATE_ID:31d9ff36-ca22-4a22-b794-c53904f614c4}
  hearingPostponed.emailId: ${HEARING_POSTPONED_EMAIL_TEMPLATE_ID:08959288-e09a-472d-80b8-af79bfcbb437}
  appealLapsed.emailId: ${APPEAL_LAPSED_EMAIL_TEMPLATE_ID:8ce8d794-75e8-49a0-b4d2-0c6cd2061c11}
  appealWithdrawn.emailId: ${APPEAL_WITHDRAWN_EMAIL_TEMPLATE_ID:8620e023-f663-477e-a771-9cfad50ee30f}
  subscriptionCreated.smsId: ${SUBSCRIPTION_CREATED_SMS_TEMPLATE_ID:18444f5f-8834-49e9-a6ae-bfe7f50db2b8}
  subscriptionUpdated.emailId: ${SUBSCRIPTION_UPDATED_EMAIL_TEMPLATE_ID:820901f0-15a9-4796-bdec-0cef42922531}
  hearingBooked.emailId: ${HEARING_BOOKED_EMAIL_TEMPLATE_ID:fee16753-0bdb-43f1-9abb-b14b826e3b26}
  evidenceReminder:
    emailId: ${EVIDENCE_REMINDER_EMAIL_TEMPLATE_ID:b9e47ec4-3b58-4b8d-9304-f77ac27fb7f2}
    smsId: ${EVIDENCE_REMINDER_SMS_TEMPLATE_ID:e3f71440-d1ac-43c8-a8cc-a088c4f3c959}
  appealCreated.emailId: ${SYA_APPEAL_CREATED_EMAIL_TEMPLATE_ID:01293b93-b23e-40a3-ad78-2c6cd01cd21c}

reminder:
  evidenceReminder.delay.seconds: 172800

---
# default profile (development, functional, smoke, production etc.)
spring:
  profiles: default
flyway:
  enabled: true
job.scheduler:
  quartzProperties:
    org.quartz:
      scheduler:
        instanceId: AUTO
      dataSource:
        jobscheduler:
          driver: org.postgresql.Driver
          URL: ${spring.datasource.url}
          user: ${spring.datasource.username}
          password: ${spring.datasource.password}
      jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        isClustered: true
        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        dataSource: jobscheduler
      threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 8
---
# integration profile
spring:
  profiles: integration
flyway:
  enabled: false
job.scheduler:
  quartzProperties:
    org.quartz:
      scheduler:
        instanceId: AUTO
      jobStore:
        class: org.quartz.simpl.RAMJobStore
---