server.port: ${PORT:8081}

spring:
  application:
    name: TyaNotificationsService
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${JOB_SCHEDULER_DB_HOST:localhost}:${JOB_SCHEDULER_DB_PORT:5432}/${JOB_SCHEDULER_DB_NAME:sscsjobscheduler}${JOB_SCHEDULER_DB_CONNECTION_OPTIONS:}
    username: ${JOB_SCHEDULER_DB_USERNAME:sscsjobscheduler}
    password: ${JOB_SCHEDULER_DB_PASSWORD:sscsjobscheduler}
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  jurisdictionId: ${CORE_CASE_DATA_JURISDICTION_ID:SSCS}
  caseTypeId: ${CORE_CASE_DATA_CASE_TYPE_ID:Benefit}

idam:
  url: ${IDAM_URL:http://localhost:4501}
  s2s-auth:
    totp_secret: ${IDAM.S2S-AUTH.TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM.S2S-AUTH.MICROSERVICE:sscs}
    url: ${IDAM.S2S-AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:SSCS_SYSTEM_UPDATE}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:SSCS_SYSTEM_UPDATE}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_OAUTH2_REDIRECT_URL:https://localhost:9000/poc}

coh:
  url: ${COH_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always

gov.uk.notification.api.key: ${NOTIFICATION_API_KEY:emailnotificationkey}
gov.uk.notification.api.testKey: ${NOTIFICATION_API_TEST_KEY:emailnotificationtestkey}
gov.uk.notification.api.testRecipients:
- "sscstest+notify@greencroftconsulting.com"
- "sscstest+notify2@greencroftconsulting.com"
- "07398785050"
- "07398785051"

subscription.hmac.secret.text: ${EMAIL_MAC_SECRET_TEXT:our-big-secret}

hmcts.phone.number: 0300 123 1142

evidence.submission.info.link: ${EVIDENCE_SUBMISSION_INFO_LINK:http://localhost:3000/evidence/appeal_id}
manage.emails.link: ${SSCS_MANAGE_EMAILS_LINK:http://localhost:3000/manage-email-notifications/mac}
track.appeal.link: ${SSCS_TRACK_YOUR_APPEAL_LINK:http://localhost:3000/trackyourappeal/appeal_id}
hearing.info.link: ${HEARING_INFO_LINK:http://localhost:3000/abouthearing/appeal_id}
claiming.expenses.link: ${CLAIMING_EXPENSES_LINK:http://localhost:3000/expenses/appeal_id}
online.hearing.link: ${ONLINE_HEARING_LINK:http://localhost:3000}

job.scheduler:
  retryPolicy:
    maxNumberOfJobExecutions: 2
    delayBetweenAttemptsInMs: 1000

notification:
  appealReceived:
    emailId: b90df52f-c628-409c-8875-4b0b9663a053
    smsId: ede384aa-0b6e-4311-9f01-ee547573a07b
  evidenceReceived:
    emailId: c5654134-2e13-4541-ac73-334a5b5cdbb6
    smsId: 74bda35f-040b-4355-bda3-faf0e4f5ae6e
  hearingAdjourned:
    emailId: bff02237-9bcb-49fa-bbf7-11725b97132a
    smsId: 46c6bf06-33dd-4e5a-9b6b-8bd6d0eb33b1
  hearingPostponed.emailId: 08959288-e09a-472d-80b8-af79bfcbb437
  appealLapsed:
    appellant:
      emailId: 8ce8d794-75e8-49a0-b4d2-0c6cd2061c11
      smsId: d2b4394b-d1c9-4d5c-a44e-b382e41c67e5
    representative:
      emailId: e93dd744-84a1-4173-847a-6d023b55637f
      smsId: ee58f7d0-8de7-4bee-acd4-252213db6b7b
  appealWithdrawn:
    appellant:
      emailId: 8620e023-f663-477e-a771-9cfad50ee30f
      smsId: 446c7b23-7342-42e1-adff-b4c367e951cb
    representative:
      emailId: e29a2275-553f-4e70-97f4-2994c095f281
      smsId: f59440ee-19ca-4d47-a702-13e9cecaccbd
  subscriptionCreated.smsId: 18444f5f-8834-49e9-a6ae-bfe7f50db2b8
  subscriptionUpdated.emailId: 820901f0-15a9-4796-bdec-0cef42922531
  hearingBooked:
    appellant:
      emailId: fee16753-0bdb-43f1-9abb-b14b826e3b26
      smsId: f900174a-a556-43b2-8042-bbf3e6090071
    representative:
      emailId: a56e67cb-6b4b-41e3-8f4c-cd1cdb6809c1
      smsId: e04c548d-1ba9-40b5-bf9b-ea5e7bbadbac
  evidenceReminder:
    emailId: b9e47ec4-3b58-4b8d-9304-f77ac27fb7f2
    smsId: e3f71440-d1ac-43c8-a8cc-a088c4f3c959
  appealCreated:
    emailId: 01293b93-b23e-40a3-ad78-2c6cd01cd21c
    smsId: f41222ef-c05c-4682-9634-6b034a166368
  hearingReminder:
    emailId: 774a5cba-fab6-4b8c-a9d9-03f913ed2dca
    smsId: 404e9a43-6318-492c-b5c2-e34ddfbbdde9
  hearingHoldingReminder:
    emailId: db8357f1-2302-49a8-a39f-2e0918cd182d
    smsId: fe4e0146-cd27-49ca-8360-465250573019
  secondHearingHoldingReminder:
    emailId: db8357f1-2302-49a8-a39f-2e0918cd182d
    smsId: fe4e0146-cd27-49ca-8360-465250573019
  thirdHearingHoldingReminder:
    emailId: db8357f1-2302-49a8-a39f-2e0918cd182d
    smsId: fe4e0146-cd27-49ca-8360-465250573019
  finalHearingHoldingReminder:
    emailId: ab66ce4e-3f18-483c-9025-f9731bad9d6e
    smsId: f1409c96-8cfa-4e92-b046-887f9599d7e4
  dwpResponseLateReminder:
    emailId: 1dfa9e4e-0a85-4001-acc9-2847ed6e2a22
    smsId: ef6297d1-7b03-432a-b04a-62a01f009b56
  question_round_issued:
    emailId: ccfbfcac-847d-4e55-955c-096802c131a0
    smsId: f4138438-9707-4d52-9f54-dfa68e96856f
  follow_up_question_round_issued:
    emailId: 71efa426-bfa9-473e-b3cf-da5d99e39461
    smsId: 217b826c-e569-4fda-b0df-45736a887af8
  question_deadline_elapsed:
    emailId: 48f2b7d1-cb71-4f60-b145-dfcf63cc4fcd
    smsId: 181fb0f5-0cc8-4d57-903f-9e5db2a76b88
  question_deadline_reminder:
    emailId: 29820a6a-1aa4-4518-8d08-f06f09c5d808
    smsId: 7a14e549-9043-47fe-bae5-5f96f8e8faa5
  continuous_online_hearing_relisted:
    emailId: 46cc347a-1a5c-40ce-993a-49769dfce626
    smsId: 31c9b4f4-0977-4382-af94-b6ef092d59f4
  decision_issued:
    emailId: 62e72e11-5eb6-4048-83f4-0b0c5c59fcb9
    smsId: 32138594-d960-44ff-8b74-07cbd565607c
  decision_issued_2:
    emailId: 5b0df251-49b9-46d5-b347-37a81ab77f19
    smsId: 04e778fd-71a8-4c27-b423-aa7485a81a9c
  online:
    responseReceived:
      emailId: 90f0ed29-a616-4ce0-b4ef-108391f5d90e
      smsId: e2e166c4-3600-443d-8feb-39f2c28e8732
    evidenceReceived:
      emailId: 0ac422c2-1585-4364-a6f0-4f42c43f85c5
      smsId: 3d3fe9cb-3cbc-479d-ab43-3a71b80b73c5
  paper:
    responseReceived:
      emailId: a64bce9a-9162-47ca-b3e7-cf5f85ca7bdc
      smsId: f5b61f94-0b2b-4e8e-9c25-56e9830df7d4
    subscriptionUpdated:
      emailId: 820901f0-15a9-4796-bdec-0cef42922531
      smsId: 18444f5f-8834-49e9-a6ae-bfe7f50db2b8
    subscriptionOld:
      emailId: 504a42dc-e135-4be3-8f86-d4109992c7f7
      smsId: c8e4b766-6c32-4225-97d9-75b14fb988b0
    appealDormant:
      emailId: 976bdb6c-8a86-48cf-9e0f-7989acaec0c2
      smsId: 1aa60c8a-1b6f-4ee1-88ae-51c1cef0ea2b
  oral:
    responseReceived:
      emailId: 1afd89f9-9935-4acb-b4f6-ba708b03a0d3
      smsId: 4bba0b5d-a3f3-4fd9-a845-26af5eda042e


smsSender:
  pip: 80b11be7-5c10-2773-8351-070e22d5ab6b
  esa: f84a568d-bd01-4940-a48a-5bcfc52940e0

reminder:
  evidenceReminder.delay.seconds: 604800
  dwpResponseLateReminder.delay.seconds: 3024000
  paperCases.decisionDate.initialDelay.seconds: 7257600
  hearingContactDate.initialDelay.seconds: 4838400
  hearingContactDate.subsequentDelay.seconds: 3628800
  hearingReminder.beforeFirst.seconds: 604800
  hearingReminder.beforeSecond.seconds: 86400

outOfHours:
  startHour: ${HOURS_START_TIME:9}
  endHour: ${HOURS_END_TIME:17}

feign:
  client:
    config:
      core-case-data-api:
        decode404: true

---
# default profile (development, production etc.)
spring:
  profiles: default
  profiles.include: ${INFRASTRUCTURE_ENV:aat}-${SLOT:STAGING}-slot
  flyway.enabled: true
job.scheduler:
  quartzProperties:
    org.quartz:
      scheduler:
        instanceId: AUTO
        idleWaitTime: ${JOB_SCHEDULER_POLL_INTERVAL:10000}
      dataSource:
        jobscheduler:
          driver: org.postgresql.Driver
          URL: ${spring.datasource.url}
          user: ${spring.datasource.username}
          password: ${spring.datasource.password}
      jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        isClustered: true
        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        dataSource: jobscheduler
      threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 8
---
# integration & functional profile
spring:
  profiles: integration, functional
  autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  flyway.enabled: false
job.scheduler:
  autoStart: false
  quartzProperties:
    org.quartz:
      scheduler:
        instanceId: AUTO
      jobStore:
        class: org.quartz.simpl.RAMJobStore
---