server.port: ${PORT:8081}

spring:
  application:
    name: TyaNotificationsService
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${JOB_SCHEDULER_DB_HOST:localhost}:${JOB_SCHEDULER_DB_PORT:5432}/${JOB_SCHEDULER_DB_NAME:sscsjobscheduler}${JOB_SCHEDULER_DB_CONNECTION_OPTIONS:}
    username: ${JOB_SCHEDULER_DB_USERNAME:sscsjobscheduler}
    password: ${JOB_SCHEDULER_DB_PASSWORD:sscsjobscheduler}
    properties:
      charSet: UTF-8
    tomcat:
      max-active: 10
      max-idle: 10
      min-idle: 2
      max-wait: 10000
      test-on-borrow: true
      test-on-connect: true
      test-on-idle: true
      validation-query: "SELECT 1"
      time-between-eviction-runs-millis: 10000
      test-while-idle: true
      test-on-return: true
      remove-abandoned: true
      remove-abandoned-timeout: 60
      log-abandoned: true
      abandon-when-percentage-full: 0

spring.main.allow-bean-definition-overriding: true  # https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#bean-overriding

core_case_data:
  api:
    url: ${CORE_CASE_DATA_API_URL:http://localhost:4452}
  jurisdictionId: SSCS
  caseTypeId: Benefit

idam:
  url: ${IDAM_URL:http://localhost:5000}
  s2s-auth:
    totp_secret: ${IDAM.S2S-AUTH.TOTP_SECRET:AAAAAAAAAAAAAAAC}
    microservice: ${IDAM.S2S-AUTH.MICROSERVICE:sscs}
    url: ${IDAM.S2S-AUTH:http://localhost:4502}
  oauth2:
    user:
      email: ${IDAM_SSCS_SYSTEMUPDATE_USER:system.update@hmcts.net}
      password: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD:Pa55word11}
    client:
      id: ${IDAM_OAUTH2_CLIENT_ID:sscs}
      secret: ${IDAM_OAUTH2_CLIENT_SECRET:QM5RQQ53LZFOSIXJ}
    redirectUrl: ${IDAM_OAUTH2_REDIRECT_URL:https://localhost:3000/authenticated}

coh:
  url: ${COH_URL:http://localhost:8081}

management:
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /
  endpoint:
    health:
      show-details: always

gov.uk.notification.api.key: ${NOTIFICATION_API_KEY:emailnotificationkey}
gov.uk.notification.api.testKey: ${NOTIFICATION_API_TEST_KEY:emailnotificationtestkey}
gov.uk.notification.api.testRecipients:
- "sscstest+notify@greencroftconsulting.com"
- "sscstest+notify2@greencroftconsulting.com"
- "07398785050"
- "07398785051"
- "+447398785050"
- "+447398785051"
- "TS1 1ST"
- "TS2 2ST"
- "TS3 3ST"

subscription.hmac.secret.text: ${EMAIL_MAC_SECRET_TEXT:our-big-secret}

evidence.submission.info.link: ${EVIDENCE_SUBMISSION_INFO_LINK:http://localhost:3000/evidence/appeal_id}
manage.emails.link: ${SSCS_MANAGE_EMAILS_LINK:http://localhost:3000/manage-email-notifications/mac}
track.appeal.link: ${SSCS_TRACK_YOUR_APPEAL_LINK:http://localhost:3000/trackyourappeal/appeal_id}
hearing.info.link: ${HEARING_INFO_LINK:http://localhost:3000/abouthearing/appeal_id}
claiming.expenses.link: ${CLAIMING_EXPENSES_LINK:http://localhost:3000/expenses/appeal_id}
online.hearing.link: ${ONLINE_HEARING_LINK:http://localhost:3000}

job.scheduler:
  retryPolicy:
    maxNumberOfJobExecutions: 2
    delayBetweenAttemptsInMs: 1000

notification:
  appealReceived:
    appellant:
      emailId: b90df52f-c628-409c-8875-4b0b9663a053
      smsId: ede384aa-0b6e-4311-9f01-ee547573a07b
      letterId: 91143b85-dd9d-430c-ba23-e42ec90f44f8
      docmosisId: TB-SCS-GNO-ENG-00060.doc
    representative:
      emailId: 4b1ee55b-abd1-4e7e-b0ed-693d8df1e741
      smsId: 99bd4a56-256c-4de8-b187-d43a8dde466f
      letterId: 77ea8a2f-06df-4279-9c1f-0f23cb2d9bbf
      docmosisId: TB-SCS-GNO-ENG-00079.doc
    appointee:
      emailId: 08365e91-9e07-4a5c-bf96-ef56fd0ada63
      smsId: ede384aa-0b6e-4311-9f01-ee547573a07b
      letterId: 747d026e-1bec-4e96-8a34-28f36e30bba5
      docmosisId: TB-SCS-GNO-ENG-00060.doc
  evidenceReceived:
    appellant:
      emailId: c5654134-2e13-4541-ac73-334a5b5cdbb6
      smsId: 74bda35f-040b-4355-bda3-faf0e4f5ae6e
      letterId: 6af62d46-98e5-4ade-aa72-e4a11c56286e
    representative:
      smsId: 345f802b-7089-4f46-a17f-bf534b272740
      letterId: 8eb75404-a442-47aa-bab2-c4ba83a70900
    appointee:
      emailId: c5654134-2e13-4541-ac73-334a5b5cdbb6
      smsId: 74bda35f-040b-4355-bda3-faf0e4f5ae6e
      letterId: 6af62d46-98e5-4ade-aa72-e4a11c56286e
  hearingAdjourned:
    appellant:
      emailId: cff1be5f-20cf-4cfa-9a90-4a75d3341ba8
      smsId: f71772b1-ae1d-49d6-87c6-a41da97a4039
    representative:
      emailId: ecf7db7d-a257-4496-a2bf-768e560c80e7
      smsId: 259b8e81-b44a-4271-a57b-ba7f8bdfcb33
    appointee:
      emailId: cff1be5f-20cf-4cfa-9a90-4a75d3341ba8
      smsId: f71772b1-ae1d-49d6-87c6-a41da97a4039
  hearingPostponed:
    appellant:
      emailId: 221095a2-aee8-466b-a7ab-beee516cc6cc
    representative:
      emailId: e07b7dba-f383-49ca-a0ba-b5b61be27da6
    appointee:
      emailId: 221095a2-aee8-466b-a7ab-beee516cc6cc
  appealLapsed:
    appellant:
      emailId: 8ce8d794-75e8-49a0-b4d2-0c6cd2061c11
      smsId: d2b4394b-d1c9-4d5c-a44e-b382e41c67e5
      letterId: 85a81e3c-a59f-4ae9-9c99-266dfd5ca95f
    representative:
      emailId: e93dd744-84a1-4173-847a-6d023b55637f
      smsId: ee58f7d0-8de7-4bee-acd4-252213db6b7b
    appointee:
      emailId: 8ce8d794-75e8-49a0-b4d2-0c6cd2061c11
      smsId: d2b4394b-d1c9-4d5c-a44e-b382e41c67e5
      letterId: 85a81e3c-a59f-4ae9-9c99-266dfd5ca95f
  dwpLapseCase:
    appellant:
      emailId: 8ce8d794-75e8-49a0-b4d2-0c6cd2061c11
      smsId: d2b4394b-d1c9-4d5c-a44e-b382e41c67e5
      letterId: 85a81e3c-a59f-4ae9-9c99-266dfd5ca95f
    representative:
      emailId: e93dd744-84a1-4173-847a-6d023b55637f
      smsId: ee58f7d0-8de7-4bee-acd4-252213db6b7b
    appointee:
      emailId: 8ce8d794-75e8-49a0-b4d2-0c6cd2061c11
      smsId: d2b4394b-d1c9-4d5c-a44e-b382e41c67e5
      letterId: 85a81e3c-a59f-4ae9-9c99-266dfd5ca95f
  hmctsLapseCase:
    appellant:
      emailId: 8ce8d794-75e8-49a0-b4d2-0c6cd2061c11
      smsId: d2b4394b-d1c9-4d5c-a44e-b382e41c67e5
      letterId: 85a81e3c-a59f-4ae9-9c99-266dfd5ca95f
    representative:
      emailId: e93dd744-84a1-4173-847a-6d023b55637f
      smsId: ee58f7d0-8de7-4bee-acd4-252213db6b7b
    appointee:
      emailId: 8ce8d794-75e8-49a0-b4d2-0c6cd2061c11
      smsId: d2b4394b-d1c9-4d5c-a44e-b382e41c67e5
      letterId: 85a81e3c-a59f-4ae9-9c99-266dfd5ca95f
  appealWithdrawn:
    appellant:
      emailId: 8620e023-f663-477e-a771-9cfad50ee30f
      smsId: 446c7b23-7342-42e1-adff-b4c367e951cb
      letterId: d4ca58d1-8b48-44eb-9af9-0bfc14a0d72d
    representative:
      emailId: e29a2275-553f-4e70-97f4-2994c095f281
      smsId: f59440ee-19ca-4d47-a702-13e9cecaccbd
      letterId: d4ca58d1-8b48-44eb-9af9-0bfc14a0d72d
    appointee:
      emailId: 8620e023-f663-477e-a771-9cfad50ee30f
      smsId: 446c7b23-7342-42e1-adff-b4c367e951cb
      letterId: d4ca58d1-8b48-44eb-9af9-0bfc14a0d72d
  subscriptionCreated:
    appellant.smsId: 7397a76f-14cb-468c-b1a7-0570940ead91
    appointee.smsId: 7397a76f-14cb-468c-b1a7-0570940ead91
    representative.smsId: a6c09fad-6265-4c7c-8b95-36245ffa5352
  subscriptionUpdated:
    emailId: b8b2904f-629d-42cf-acea-1b74bde5b2ff
    smsId: 7397a76f-14cb-468c-b1a7-0570940ead91
  subscriptionOld:
    emailId: 03b957bf-e21d-4147-90c1-b6fefa8cf70d
    smsId: 759c712a-6b55-485e-bcf7-1cf5c4896eb1
  hearingBooked:
    appellant:
      emailId: fee16753-0bdb-43f1-9abb-b14b826e3b26
      smsId: 693c9bfb-151e-4add-a6f2-af1cbc94eef5
      letterId: 22e51eec-6ba9-489a-aea0-a9e919716935
    representative:
      emailId: a56e67cb-6b4b-41e3-8f4c-cd1cdb6809c1
      smsId: e04c548d-1ba9-40b5-bf9b-ea5e7bbadbac
      letterId: 9046261e-11c5-43e5-8aa6-dd7a786b82c4
    appointee:
      emailId: fee16753-0bdb-43f1-9abb-b14b826e3b26
      smsId: 693c9bfb-151e-4add-a6f2-af1cbc94eef5
      letterId: 22e51eec-6ba9-489a-aea0-a9e919716935
  appealCreated:
    appellant:
      emailId: 01293b93-b23e-40a3-ad78-2c6cd01cd21c
      smsId: f41222ef-c05c-4682-9634-6b034a166368
      letterId: 91143b85-dd9d-430c-ba23-e42ec90f44f8
    representative:
      emailId: 652753bf-59b4-46eb-9c24-bd762338a098
      smsId: a6c09fad-6265-4c7c-8b95-36245ffa5352
      letterId: 77ea8a2f-06df-4279-9c1f-0f23cb2d9bbf
    appointee:
      emailId: 362d9a85-e0e4-412b-b874-020c0464e2b4
      smsId: f41222ef-c05c-4682-9634-6b034a166368
      letterId: 747d026e-1bec-4e96-8a34-28f36e30bba5
  validAppealCreated:
    appellant:
      emailId: 01293b93-b23e-40a3-ad78-2c6cd01cd21c
      smsId: f41222ef-c05c-4682-9634-6b034a166368
      letterId: 91143b85-dd9d-430c-ba23-e42ec90f44f8
    representative:
      emailId: 652753bf-59b4-46eb-9c24-bd762338a098
      smsId: a6c09fad-6265-4c7c-8b95-36245ffa5352
      letterId: 77ea8a2f-06df-4279-9c1f-0f23cb2d9bbf
    appointee:
      emailId: 362d9a85-e0e4-412b-b874-020c0464e2b4
      smsId: f41222ef-c05c-4682-9634-6b034a166368
      letterId: 747d026e-1bec-4e96-8a34-28f36e30bba5
  resendAppealCreated:
    appellant:
      emailId: 01293b93-b23e-40a3-ad78-2c6cd01cd21c
      smsId: f41222ef-c05c-4682-9634-6b034a166368
    representative:
      emailId: 652753bf-59b4-46eb-9c24-bd762338a098
      smsId: a6c09fad-6265-4c7c-8b95-36245ffa5352
  hearingReminder:
    appellant:
      emailId: 774a5cba-fab6-4b8c-a9d9-03f913ed2dca
      smsId: fcb93790-8308-4f4f-9674-65b777b7fe8c
    appointee:
      emailId: 774a5cba-fab6-4b8c-a9d9-03f913ed2dca
      smsId: fcb93790-8308-4f4f-9674-65b777b7fe8c
    representative:
      emailId: 97c58e23-c11f-40b3-b981-2d4cfa38b8fd
      smsId: bb3df0ea-8259-43c4-95de-9eef96206575
  question_round_issued:
    emailId: ccfbfcac-847d-4e55-955c-096802c131a0
  follow_up_question_round_issued:
    emailId: 71efa426-bfa9-473e-b3cf-da5d99e39461
  question_deadline_elapsed:
    emailId: 48f2b7d1-cb71-4f60-b145-dfcf63cc4fcd
  question_deadline_reminder:
    emailId: 29820a6a-1aa4-4518-8d08-f06f09c5d808
  continuous_online_hearing_relisted:
    emailId: 46cc347a-1a5c-40ce-993a-49769dfce626
  decision_issued:
    emailId: 62e72e11-5eb6-4048-83f4-0b0c5c59fcb9
  directionIssued:
    appellant:
      docmosisId: TB-SCS-GNO-ENG-00067.docx
    appointee:
      docmosisId: TB-SCS-GNO-ENG-00067.docx
    representative:
      docmosisId: TB-SCS-GNO-ENG-00089.docx
  decisionIssued:
    appellant:
      docmosisId: TB-SCS-GNO-ENG-00094.docx
    appointee:
      docmosisId: TB-SCS-GNO-ENG-00094.docx
    representative:
      docmosisId: TB-SCS-GNO-ENG-00095.docx
  corDecision:
    emailId: 5b0df251-49b9-46d5-b347-37a81ab77f19
  requestInfoIncompleteApplication:
    appellant:
      letterId: bc943cf3-9fd1-4d14-a0c0-b183572c21a7
    representative:
      letterId: a2a4a88a-b91a-4e6d-94f0-507179292058
    appointee:
      letterId: bc943cf3-9fd1-4d14-a0c0-b183572c21a7
  nonCompliant:
    appellant:
      letterId: 114cadaa-7760-4699-9add-d3a252f68909
    representative:
      letterId: 5745f77c-6512-4082-8c34-63851f24eab1
    appointee:
      letterId: 114cadaa-7760-4699-9add-d3a252f68909
  online:
    responseReceived:
      emailId: 90f0ed29-a616-4ce0-b4ef-108391f5d90e
    dwpUploadResponse:
      emailId: 90f0ed29-a616-4ce0-b4ef-108391f5d90e
    evidenceReceived:
      emailId: 0ac422c2-1585-4364-a6f0-4f42c43f85c5
  paper:
    responseReceived:
      appellant:
        emailId: e1084d78-5e2d-45d2-a54f-84339da141c1
        smsId: 505be856-ceca-4bbc-ba70-29024585056f
      appointee:
        emailId: e1084d78-5e2d-45d2-a54f-84339da141c1
        smsId: 505be856-ceca-4bbc-ba70-29024585056f
      representative:
        emailId: 5abc83d8-f6b8-4385-805b-ffbb0f64b84b
        smsId: b2d187cd-089b-4fe1-b460-a310c0af46fe
    dwpUploadResponse:
      appellant:
        emailId: e1084d78-5e2d-45d2-a54f-84339da141c1
        smsId: 505be856-ceca-4bbc-ba70-29024585056f
        letterId: 16c141bc-4e16-48ed-8b60-4db58207201c
      appointee:
        emailId: e1084d78-5e2d-45d2-a54f-84339da141c1
        smsId: 505be856-ceca-4bbc-ba70-29024585056f
        letterId: 16c141bc-4e16-48ed-8b60-4db58207201c
      representative:
        emailId: 8dc0510c-70d5-4791-9217-87d70361a54c
        smsId: b2d187cd-089b-4fe1-b460-a310c0af46fe
        letterId: 59a392a1-5946-4e55-ac82-048fd32b15a5
    appealDormant:
      appellant:
        emailId: 976bdb6c-8a86-48cf-9e0f-7989acaec0c2
        smsId: 1aa60c8a-1b6f-4ee1-88ae-51c1cef0ea2b
      representative:
        emailId: b74ea5d4-dba2-4148-b822-d102cedbea12
        smsId: 4562984e-2854-4191-81d9-cffbe5111015
    evidenceReminder:
      appellant:
        emailId: a3b22e07-e90b-4b52-a293-30823802c209
        smsId: aaa1aad4-7abc-4a7a-b8fb-8b0567c09365
      appointee:
        emailId: a3b22e07-e90b-4b52-a293-30823802c209
        smsId: aaa1aad4-7abc-4a7a-b8fb-8b0567c09365
      representative:
        emailId: 81fa38cc-b7cc-469c-8109-67c801dc9c84
        smsId: f1076482-a76d-4389-b411-9865373cfc42
    evidenceReceived:
      appellant:
        emailId: cab48431-a4f0-41f5-b753-2cecf20ab5d4
      representative:
        emailId: 7af36950-fc63-45d1-907d-f472fac7af06
        smsId: 345f802b-7089-4f46-a17f-bf534b272740
      appointee:
        emailId: c5654134-2e13-4541-ac73-334a5b5cdbb6
        smsId: 74bda35f-040b-4355-bda3-faf0e4f5ae6e
  oral:
    responseReceived:
      appellant:
        emailId: 2c5644db-1f7b-429b-b10a-8b23a80ed26a
        smsId: f20ffcb1-c5f0-4bff-b2d1-a1094f8014e6
        letterId: 8b11f3f4-6452-4a35-93d8-a94996af6499
      appointee:
        emailId: 2c5644db-1f7b-429b-b10a-8b23a80ed26a
        smsId: f20ffcb1-c5f0-4bff-b2d1-a1094f8014e6
        letterId: 8b11f3f4-6452-4a35-93d8-a94996af6499
      representative:
        emailId: 0d844af4-b390-42d7-94d5-4fd1ae9388d9
        smsId: 9fe3a4f1-b8e2-4aed-aafb-6360d6ba2874
        letterId: 419beb1c-4f26-45e7-8db3-69bfe5e9224d
    dwpUploadResponse:
      appellant:
        emailId: 2c5644db-1f7b-429b-b10a-8b23a80ed26a
        smsId: f20ffcb1-c5f0-4bff-b2d1-a1094f8014e6
        letterId: 8b11f3f4-6452-4a35-93d8-a94996af6499
      appointee:
        emailId: 2c5644db-1f7b-429b-b10a-8b23a80ed26a
        smsId: f20ffcb1-c5f0-4bff-b2d1-a1094f8014e6
        letterId: 8b11f3f4-6452-4a35-93d8-a94996af6499
      representative:
        emailId: 0d844af4-b390-42d7-94d5-4fd1ae9388d9
        smsId: 9fe3a4f1-b8e2-4aed-aafb-6360d6ba2874
        letterId: 419beb1c-4f26-45e7-8db3-69bfe5e9224d
    evidenceReminder:
      appellant:
        emailId: b9e47ec4-3b58-4b8d-9304-f77ac27fb7f2
        smsId: e3f71440-d1ac-43c8-a8cc-a088c4f3c959
      appointee:
        emailId: b9e47ec4-3b58-4b8d-9304-f77ac27fb7f2
        smsId: e3f71440-d1ac-43c8-a8cc-a088c4f3c959
      representative:
        emailId: df0803aa-f804-49fe-a2ac-c27adc4bb585
        smsId: 5f91012e-0d3f-465b-b301-ee3ee5a50100
    evidenceReceived:
      representative:
        emailId: 30260c0b-5575-4f4e-bce4-73cf3f245c2d
    appealDormant:
      appellant:
        emailId: fc9d0618-68c4-48ec-9481-a84b225a57a9
      representative:
        emailId: e2ee8609-7d56-4857-b3f8-79028e8960aa

smsSender:
  pip: 80b11be7-5c10-2773-8351-070e22d5ab6b
  esa: f84a568d-bd01-4940-a48a-5bcfc52940e0
  uc: 2811c776-2d38-4413-96c6-efa639eabc40

reminder:
  evidenceReminder.delay.seconds: 604800
  dwpResponseLateReminder.delay.seconds: 3024000
  paperCases.decisionDate.initialDelay.seconds: 7257600
  hearingContactDate.initialDelay.seconds: 4838400
  hearingContactDate.subsequentDelay.seconds: 3628800
  hearingReminder.beforeFirst.seconds: 604800
  hearingReminder.beforeSecond.seconds: 86400

outOfHours:
  startHour: ${HOURS_START_TIME:9}
  endHour: ${HOURS_END_TIME:17}

feign:
  client:
    config:
      core-case-data-api:
        decode404: true

# Document store
document_management.url: ${DOCUMENT_MANAGEMENT_URL:http://dm-store:5005}

appeal.email.host: ${EMAIL_SERVER_HOST:localhost}
appeal.email.port: ${EMAIL_SERVER_PORT:1025}
appeal.email.smtp.tls.enabled: ${EMAIL_SMTP_TLS_ENABLED:true}
appeal.email.smtp.ssl.trust: ${EMAIL_SMTP_SSL_TRUST:*}

appeal.email.from: ${EMAIL_FROM:sscs@hmcts.net}
appeal.email.to: ${EMAIL_TO:receiver@hmcts.net}
appeal.email.subject: ${EMAIL_SUBJECT:Your appeal}
appeal.email.message: ${EMAIL_MESSAGE:Your appeal has been created \nPlease do not respond to this email}

appellant.appeal.html.template.path: /templates/appellant_appeal_template.html
strikeOutLetterTemplate.appelant.appeal.html.template.path: /templates/strike_out_letter_template.html
strikeOutLetterTemplate.rep.appeal.html.template.path: /templates/strike_out_letter_template_rep.html
validAppealCreatedLetterTemplate.appellant.appeal.html.template.path: /templates/valid_appeal_created_template.html
validAppealCreatedLetterTemplate.rep.appeal.html.template.path: /templates/valid_appeal_created_template_rep.html

pdf.api.url: ${PDF_API_URL:http://localhost:5500}

robotics.email.from: ${ROBOTICS_EMAIL_FROM:sscs@hmcts.net}
robotics.email.to: ${ROBOTICS_EMAIL_TO:receiver@hmcts.net}
robotics.email.subject: ${ROBOTICS_EMAIL_SUBJECT:Robotics Data}
robotics.email.message: ${ROBOTICS_EMAIL_MESSAGE:Please find attached the robotics json file \nPlease do not respond to this email}
robotics.schema.resource.location: /schema/sscs-robotics.json

feature.bundled_letters_on: ${BUNDLED_LETTERS_ON:true}
feature.letters_on: ${LETTERS_ON:true}
feature.docmosis_letters_on: ${DOCMOSIS_LETTERS_ON:true}
feature.interloc_letters_on: ${INTERLOC_LETTERS_ON:true}
feature.docmosis_leters.appealReceived_on: ${APPEAL_RECEIVED_LETTER_ON:true}
feature.docmosis_leters.directionIssued_on: true
feature.docmosis_leters.decisionIssued_on: true
feature.save_correspondence: ${SAVE_CORRESPONDENCE:true}
feature.readyToListRobotics_on: ${READY_TO_LIST_ROBOTICS_ENABLED:true}

letterAsync:
  maxAttempts: ${LETTER_ASYNC_MAX_ATTEMPTS:5}
  delay: ${LETTER_ASYNC_DELAY:3000}
  multiplier: ${LETTER_ASYNC_MULTIPLIER:10}

pdf-service:
  uri: ${PDF_SERVICE_BASE_URL:https://docmosis-development.platform.hmcts.net/rs/render}
  accessKey: ${PDF_SERVICE_ACCESS_KEY:secret-key-not-supplied}
  health:
    uri: ${PDF_SERVICE_HEALTH_URL:https://docmosis-development.platform.hmcts.net/rs/status}
  hmctsImgKey: hmcts2
  hmctsImgVal: "[userImage:hmcts-2.png]"
  coverSheets:
    appealReceived: 'TB-SCS-GNO-ENG-00012.docx'
    directionIssued: 'TB-SCS-GNO-ENG-00012.docx'
    decisionIssued: 'TB-SCS-GNO-ENG-00012.docx'

amqp:
  host: ${AMQP_HOST:localhost}
  username: ${AMQP_USERNAME:guest}
  password: ${AMQP_PASSWORD:guest}
  topic: ${TOPIC_NAME:test.topic}
  subscription: ${SUBSCRIPTION_NAME:test2.queue}
  # DO NOT SET THIS 'true' IN PRODUCTION!
  trustAllCerts: ${TRUST_ALL_CERTS:true}

---
# default profile (development, production etc.)
spring:
  profiles: default
  profiles.include: ${INFRASTRUCTURE_ENV:aat}-${SLOT:STAGING}-slot
  flyway.enabled: true
job.scheduler:
  quartzProperties:
    org.quartz:
      scheduler:
        instanceId: AUTO
        idleWaitTime: ${JOB_SCHEDULER_POLL_INTERVAL:10000}
      dataSource:
        jobscheduler:
          driver: org.postgresql.Driver
          URL: ${spring.datasource.url}
          user: ${spring.datasource.username}
          password: ${spring.datasource.password}
      jobStore:
        class: org.quartz.impl.jdbcjobstore.JobStoreTX
        isClustered: true
        driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
        dataSource: jobscheduler
      threadPool:
        class: org.quartz.simpl.SimpleThreadPool
        threadCount: 8
evidence:
  address:
    line1:
    line2: HMCTS SSCS
    line3: PO BOX 12626
    town: Harlow
    county: Essex
    postcode: CM20 9QF
    telephone: 0300 123 1142
---
# integration & functional profile
spring:
  profiles: integration, functional
  autoconfigure.exclude:
  - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  flyway.enabled: false
job.scheduler:
  autoStart: false
  quartzProperties:
    org.quartz:
      scheduler:
        instanceId: AUTO
      jobStore:
        class: org.quartz.simpl.RAMJobStore
