name: sscs-tya-notif
description: SSCS Track Your Appeal Notifications
home: https://github.com/hmcts/sscs-track-your-appeal-notifications
apiVersion: v2
appVersion: "1.0"
version: 0.0.45
maintainers:
  - name: HMCTS SSCS Team
dependencies:
  - name: java
    version: 5.0.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
