java:
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    COH_URL: "http://coh-cor-aat.service.core-compute-aat.internal"
    ONLINE_HEARING_LINK: "https://sscs-cor-frontend-aat.service.core-compute-aat.internal"
    EVIDENCE_SUBMISSION_INFO_LINK: "https://track-appeal.aat.platform.hmcts.net/evidence/appeal_id"
    SSCS_MANAGE_EMAILS_LINK: "https://track-appeal.aat.platform.hmcts.net/manage-email-notifications/mac"
    HEARING_INFO_LINK: "https://track-appeal.aat.platform.hmcts.net/abouthearing/appeal_id"
    CLAIMING_EXPENSES_LINK: "https://track-appeal.aat.platform.hmcts.net/expenses/appeal_id"
    IDAM_S2S_AUTH: "http://rpe-service-auth-provider-aat.service.core-compute-aat.internal"
    IDAM_API_URL: "https://idam-api.aat.platform.hmcts.net"
    IDAM_SSCS_SYSTEMUPDATE_USER: ${IDAM_SSCS_SYSTEMUPDATE_USER}
    IDAM_SSCS_SYSTEMUPDATE_PASSWORD: ${IDAM_SSCS_SYSTEMUPDATE_PASSWORD}
    IDAM_OAUTH2_CLIENT_SECRET: ${IDAM_OAUTH2_CLIENT_SECRET}
    IDAM_S2S_AUTH_MICROSERVICE: ${IDAM_S2S_AUTH_MICROSERVICE}
    IDAM_S2S_AUTH_TOTP_SECRET: ${IDAM_S2S_AUTH_TOTP_SECRET}
    NOTIFICATION_API_KEY: ${NOTIFICATION_API_KEY}
    NOTIFICATION_API_TEST_KEY: ${NOTIFICATION_API_TEST_KEY}
    EMAIL_MAC_SECRET_TEXT: ${EMAIL_MAC_SECRET_TEXT}
    PDF_SERVICE_BASE_URL: ${PDF_SERVICE_BASE_URL}rs/render
    PDF_SERVICE_ACCESS_KEY: ${PDF_SERVICE_ACCESS_KEY}
    PDF_SERVICE_HEALTH_URL: ${PDF_SERVICE_BASE_URL}rs/status
    HOURS_START_TIME: 0
    HOURS_END_TIME: 23
postgresql:
  enabled: true
