java:
  image: 'https://hmctspublic.azurecr.io/sscs/tya-notif:latest'
  applicationPort: 8081
  readinessPath: '/health/readiness'
  aadIdentityName: sscs
  ingressHost: sscs-tya-notif-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal
  keyVaults:
    sscs:
      secrets:
      - idam-api
        alias: idam.url
      - idam-oauth-user
        alias: idam.oauth2.client.id
      - idam-redirect
        alias: idam.oauth2.redirectUrl
      - idam-sscs-systemupdate-user
        alias: idam.oauth2.user.email
      - idam-sscs-systemupdate-password
        alias: idam.oauth2.user.password
      - sscs-email-mac-secret-text
        alias: subscription.hmac.secret.text
      - idam-sscs-oauth2-client-secret
        alias: IDAM_OAUTH2_CLIENT_SECRET
      - sscs-s2s-secret
        alias: IDAM_S2S_AUTH_TOTP_SECRET
      - s2s-micro
      - sscs-asb-primary-send-and-listen-shared-access-key
        alias: AMQP_PASSWORD
      - docmosis-api-key
        alias: PDF_SERVICE_ACCESS_KEY
      - notification-job-scheduler-db-password
        alias: spring.datasource.password
      - notification-key
        alias: NOTIFICATION_API_KEY
      - notification-test-key
        alias: NOTIFICATION_API_TEST_KEY
      - AppInsightsInstrumentationKey
        alias: azure.application-insights.instrumentation-key
  environment:
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: tya-notifications
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    INFRASTRUCTURE_ENV: preprod
    CORE_CASE_DATA_JURISDICTION_ID: SSCS
    CORE_CASE_DATA_CASE_TYPE_ID: Benefit
    JOB_SCHEDULER_POLL_INTERVAL: "30000"
    JOB_SCHEDULER_DB_PORT: "5432"
    JOB_SCHEDULER_DB_USERNAME: "notification@sscs-tya-notif-postgres-v11-db-{{ .Values.global.environment }}"
    JOB_SCHEDULER_DB_NAME: "notification"
    JOB_SCHEDULER_DB_HOST: "sscs-tya-notif-postgres-v11-db-{{ .Values.global.environment }}.postgres.database.azure.com"
    IDAM_OAUTH2_REDIRECT_URL: "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
    EVIDENCE_SUBMISSION_INFO_LINK: "https://track-appeal.{{ .Values.global.environment }}.platform.hmcts.net/evidence/appeal_id"
    SSCS_MANAGE_EMAILS_LINK: "https://sscs-cor.{{ .Values.global.environment }}.platform.hmcts.net/manage-email-notifications/mac"
    SSCS_TRACK_YOUR_APPEAL_LINK: "https://track-appeal.nonprod.platform.hmcts.net/trackyourappeal/appeal_id"
    MYA_LINK: "https://sscs-cor.aat.platform.hmcts.net/sign-in?tya=appeal_id"
    HEARING_INFO_LINK: "https://track-appeal.{{ .Values.global.environment }}.platform.hmcts.net/abouthearing/appeal_id"
    CLAIMING_EXPENSES_LINK: "https://track-appeal.{{ .Values.global.environment }}.platform.hmcts.net/expenses/appeal_id"
    MYA_EVIDENCE_LINK: "https://sscs-cor.aat.platform.hmcts.net/support-evidence"
    MYA_HEARING_LINK: "https://sscs-cor.aat.platform.hmcts.net/support-hearing"
    MYA_EXPENSES_LINK: "https://sscs-cor.aat.platform.hmcts.net/support-hearing-expenses"
    IDAM_S2S_AUTH: "http://rpe-service-auth-provider-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    IDAM_API_URL: "https://idam-api.{{ .Values.global.environment }}.platform.hmcts.net"
    CORE_CASE_DATA_API_URL: "http://ccd-data-store-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    DOCUMENT_MANAGEMENT_URL: "http://dm-store-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    COH_URL: "http://coh-cor-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    ONLINE_HEARING_LINK: "https://sscs-cor-frontend-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    PDF_API_URL: "http://rpe-pdf-service-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    CASE_DOCUMENT_AM_URL: "http://ccd-case-document-am-api-{{ .Values.global.environment }}.service.core-compute-{{ .Values.global.environment }}.internal"
    JOB_SCHEDULER_DB_CONNECTION_OPTIONS: ?sslmode=require
    MAX_ACTIVE_DB_CONNECTIONS: 70
    HOURS_START_TIME: 5
    HOURS_END_TIME: 17
    TRUST_ALL_CERTS: "false"
    SUBSCRIPTION_NAME: "sscs-notifications-subscription-{{ .Values.global.environment }}"
    TOPIC_NAME: "sscs-evidenceshare-topic-{{ .Values.global.environment }}"
    AMQP_HOST: "sscs-servicebus-{{ .Values.global.environment }}.servicebus.windows.net"
    AMQP_USERNAME: "SendAndListenSharedAccessKey"
    PDF_SERVICE_HEALTH_URL: https://docmosis.aat.platform.hmcts.net/rs/status
    PDF_SERVICE_BASE_URL: https://docmosis.aat.platform.hmcts.net/rs/render
    RUN_DB_MIGRATION_ON_STARTUP: false
