postgresql:
  postgresqlUsername: sscs
  postgresqlPassword: sscs
  postgresqlDatabase: preview
  persistence:
    enabled: false
  service:
    type: LoadBalancer
    annotations:
      service.beta.kubernetes.io/azure-load-balancer-internal: "true"

java:
  image: 'https://hmctspublic.azurecr.io/sscs/tya-notif:latest'
  applicationPort: 8081
  keyVaults:
    sscs:
      resourceGroup: sscs
      secrets:
      - idam-api
      - idam-oauth-user
      - idam-redirect
      - idam-sscs-systemupdate-user
      - idam-sscs-systemupdate-password
      - idam-sscs-oauth2-client-secret
      - ccd-api
      - ccd-jid
      - ccd-tid
      - idam-s2s-api
      - sscs-s2s-secret
      - s2s-micro
      - sscs-asb-primary-send-and-listen-shared-access-key
      - docmosis-endpoint
      - docmosis-api-key
  environment:
    REFORM_TEAM: sscs
    REFORM_SERVICE_NAME: tya-notifications
    REFORM_SERVICE_TYPE: java
    REFORM_ENVIRONMENT: preview
    ROOT_LOGGING_LEVEL: INFO
    LOG_OUTPUT: single
    IDAM_OAUTH2_CLIENT_ID: "sscs"
    INFRASTRUCTURE_ENV: preprod
    CORE_CASE_DATA_JURISDICTION_ID: SSCS
    CORE_CASE_DATA_CASE_TYPE_ID: Benefit
    JOB_SCHEDULER_POLL_INTERVAL: "30000"
    JOB_SCHEDULER_DB_PORT: "5432"
    JOB_SCHEDULER_DB_PASSWORD:  "{{ .Values.postgresql.postgresqlPassword}}"
    JOB_SCHEDULER_DB_USERNAME: "{{ .Values.postgresql.postgresqlUsername}}"
    JOB_SCHEDULER_DB_NAME: "{{ .Values.postgresql.postgresqlDatabase}}"
    JOB_SCHEDULER_DB_CONNECTION_OPTIONS: ""
    MAX_ACTIVE_DB_CONNECTIONS: 70
    HOURS_START_TIME: 0
    HOURS_END_TIME: 23
    TRUST_ALL_CERTS: "false"
    SUBSCRIPTION_NAME: "sscs-notifications-subscription-{{ .Values.global.environment }}"
    TOPIC_NAME: "sscs-evidenceshare-topic-{{ .Values.global.environment }}"
    AMQP_HOST: "sscs-servicebus-{{ .Values.global.environment }}.servicebus.windows.net"
    AMQP_USERNAME: "SendAndListenSharedAccessKey"


