management_security_enabled = "false"
infrastructure_env = "preprod"

evidence_submission_info_link = "https://track-appeal.preview.platform.hmcts.net/evidence/appeal_id"
sscs_manage_emails_link = "https://track-appeal.preview.platform.hmcts.net/manage-email-notifications/mac"
sscs_track_your_appeal_link = "https://track-appeal.preview.platform.hmcts.net/trackyourappeal/appeal_id"
hearing_info_link = "https://track-appeal.preview.platform.hmcts.net/abouthearing/appeal_id"
claiming_expenses_link = "https://track-appeal.preview.platform.hmcts.net/expenses/appeal_id"

root_logging_level = "DEBUG"
log_level_spring_web = "DEBUG"
log_level_sscs = "DEBUG"
idam_redirect_url = "https://evidence-sharing-preprod.sscs.reform.hmcts.net"
notification_key = "notification-key"
notification_test_key = "notification-test-key"