infrastructure_env = "test"

evidence_submission_info_link = "https://sscs-track-your-appeal-frontend-saat.service.core-compute-saat.internal/evidence/appeal_id"
sscs_manage_emails_link = "https://sscs-track-your-appeal-frontend-saat.service.core-compute-saat.internal/mac"
sscs_track_your_appeal_link = "https://sscs-track-your-appeal-frontend-saat.service.core-compute-saat.internal/appeal_id"
hearing_info_link = "https://sscs-track-your-appeal-frontend-saat.service.core-compute-saat.internal/abouthearing/appeal_id"
claiming_expenses_link = "https://sscs-track-your-appeal-frontend-saat.service.core-compute-saat.internal/expenses/appeal_id"
core_case_data_user_id = "43132"
idam_redirect_url = "https://sscs-case-loader-aat.service.core-compute-aat.internal"
notification_key = "notification-key"
notification_test_key = "notification-test-key"
