package uk.gov.hmcts.sscs.model;


public enum ReminderType {
    APPEAL_RECEIVED,
    DWP_RESPOND,
    DORMANT,
    HEARING_BOOKED,
    HEARING_REMINDER,
    HEARING,
    EVIDENCE_RECEIVED,
    EVIDENCE_REMINDER,
    EVIDENCE_EMAIL,
    EVIDENCE_SMS_DAY_NO_EVIDENCE,
    EVIDENCE_SMS_DAY_WITH_EVIDENCE,
    HEARING_EMAIL_DAY,
    HEARING_EMAIL_WEEK,
    HEARING_SMS_DAY,
    HEARING_SMS_WEEK,
    LAPSED_REVISED,
    WITHDRAWN,
    ADJOURNED,
    POSTPONED,
    SUPPORTER_SUBSCRIBE,
    APPELLANT_UPDATE_NEW_SUBSCRIBE,
    HEARING_REMINDER_1, APPELLANT_SUBSCRIBE, APPELLANT_UPDATE_OLD_SUBSCRIBE
}
